"use client";

import { useState, useCallback } from "react";
import { ToolPageLayout } from "@/components/layout/ToolPageLayout";
import { names as usNames } from "@/data/names/us";
import { emailDomains } from "@/data/domains";

const faqs = [
  {
    question: "Are these real email addresses?",
    answer:
      "No. These are randomly generated email addresses that combine random names with email domain names. They are not real inboxes and cannot send or receive mail.",
  },
  {
    question: "Can I use these for testing?",
    answer:
      "Yes! These are ideal for populating test databases, filling out forms during development, and any scenario where you need realistic-looking email addresses without using real ones.",
  },
  {
    question: "What email domains are available?",
    answer:
      "Common domains include gmail.com, yahoo.com, hotmail.com, outlook.com, and more. You can also enter a custom domain to generate emails for your own domain.",
  },
  {
    question: "How are the email addresses generated?",
    answer:
      "Email addresses are generated by combining random first and last names with separators like dots or numbers, then appending a random or custom email domain.",
  },
];

function pickRandom<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function generateEmails(count: number, domainType: string, customDomain: string): string[] {
  const results: string[] = [];
  const separators = [".", "_", ""];

  for (let i = 0; i < count; i++) {
    const gender = Math.random() > 0.5 ? "male" : "female";
    const first = pickRandom(usNames[gender]).toLowerCase();
    const last = pickRandom(usNames.last).toLowerCase();
    const sep = pickRandom(separators);
    const num = Math.random() > 0.5 ? String(Math.floor(Math.random() * 999)) : "";

    const patterns = [
      `${first}${sep}${last}${num}`,
      `${first}${num}`,
      `${first}${sep}${last.charAt(0)}${num}`,
      `${last}${sep}${first}${num}`,
      `${first.charAt(0)}${sep}${last}${num}`,
    ];

    const username = pickRandom(patterns);
    const domain = domainType === "custom" && customDomain ? customDomain : pickRandom(emailDomains);
    results.push(`${username}@${domain}`);
  }
  return results;
}

export function EmailClient() {
  const [domainType, setDomainType] = useState("common");
  const [customDomain, setCustomDomain] = useState("example.com");
  const [count, setCount] = useState(5);
  const [emails, setEmails] = useState<string[]>(() => generateEmails(5, "common", ""));
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  const generate = useCallback(() => {
    setEmails(generateEmails(count, domainType, customDomain));
    setCopiedIndex(null);
  }, [count, domainType, customDomain]);

  const copyEmail = async (email: string, index: number) => {
    await navigator.clipboard.writeText(email);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  const copyAll = async () => {
    await navigator.clipboard.writeText(emails.join("\n"));
    setCopiedIndex(-1);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  return (
    <ToolPageLayout
      title="Random Email Generator"
      description="Generate random fake email addresses for testing and development. Choose common domains or use a custom domain."
      slug="email-generator"
      faqs={faqs}
      seoContent={
        <>
          <h2>About the Random Email Generator</h2>
          <p>
            Generate realistic-looking email addresses for testing and development. Our email
            generator combines real first and last names with popular email domains to create
            addresses that look authentic.
          </p>
          <h3>Features</h3>
          <ul>
            <li>Generate up to 20 email addresses at once</li>
            <li>Use common email domains like Gmail, Yahoo, and Outlook</li>
            <li>Specify a custom domain for company-specific testing</li>
            <li>Various username formats including first.last, firstlast, and more</li>
          </ul>
          <h3>Use Cases</h3>
          <ul>
            <li>Populating test databases with sample user emails</li>
            <li>Testing email validation and form inputs</li>
            <li>Creating demo accounts for presentations</li>
            <li>QA testing for email-related features</li>
          </ul>
        </>
      }
    >
      {/* Options */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">Domain Type</label>
          <select
            value={domainType}
            onChange={(e) => setDomainType(e.target.value)}
            className="input w-full"
          >
            <option value="common">Common Domains</option>
            <option value="custom">Custom Domain</option>
          </select>
        </div>
        {domainType === "custom" && (
          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">Custom Domain</label>
            <input
              type="text"
              value={customDomain}
              onChange={(e) => setCustomDomain(e.target.value)}
              className="input w-full"
              placeholder="example.com"
            />
          </div>
        )}
        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">
            Count ({count})
          </label>
          <input
            type="range"
            min={1}
            max={20}
            value={count}
            onChange={(e) => setCount(Number(e.target.value))}
            className="w-full accent-indigo-600"
          />
        </div>
      </div>

      <button onClick={generate} className="btn-primary w-full mb-6">
        Generate Emails
      </button>

      {/* Results */}
      <div className="space-y-2">
        <div className="flex justify-between items-center mb-2">
          <span className="text-sm text-slate-500">{emails.length} emails generated</span>
          <button onClick={copyAll} className="copy-btn text-xs">
            {copiedIndex === -1 ? "Copied!" : "Copy All"}
          </button>
        </div>
        {emails.map((email, i) => (
          <div
            key={i}
            className="flex items-center justify-between bg-slate-50 border border-slate-200 rounded-lg px-4 py-2"
          >
            <span className="font-mono text-sm text-slate-800 truncate">{email}</span>
            <button
              onClick={() => copyEmail(email, i)}
              className="copy-btn text-xs shrink-0 ml-3"
            >
              {copiedIndex === i ? "Copied!" : "Copy"}
            </button>
          </div>
        ))}
      </div>
    </ToolPageLayout>
  );
}
